TYPE=VIEW
query=select `asterisk`.`users`.`extension` AS `extension`,`asterisk`.`users`.`name` AS `name`,\'from-did-direct\' AS `context`,\'extension\' AS `type` from `asterisk`.`users` union select `asterisk`.`queues_config`.`extension` AS `extension`,`asterisk`.`queues_config`.`descr` AS `descr`,\'ext-queues\' AS `context`,\'queue\' AS `type` from `asterisk`.`queues_config` union select `asterisk`.`ringgroups`.`grpnum` AS `grpnum`,`asterisk`.`ringgroups`.`description` AS `description`,\'ext-group\' AS `context`,\'ringgroup\' AS `type` from `asterisk`.`ringgroups`
md5=8b5c1d8cc4307953ea526b8dce2a622d
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2025-02-14 00:19:53
create-version=1
source=select `users`.`extension` AS `extension`,`users`.`name` AS `name`,\'from-did-direct\' AS `context`,\'extension\' AS `type` from `users` union select `queues_config`.`extension` AS `extension`,`queues_config`.`descr` AS `descr`,\'ext-queues\' AS `context`,\'queue\' AS `type` from `queues_config` union select `ringgroups`.`grpnum` AS `grpnum`,`ringgroups`.`description` AS `description`,\'ext-group\' AS `context`,\'ringgroup\' AS `type` from `ringgroups`
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `asterisk`.`users`.`extension` AS `extension`,`asterisk`.`users`.`name` AS `name`,\'from-did-direct\' AS `context`,\'extension\' AS `type` from `asterisk`.`users` union select `asterisk`.`queues_config`.`extension` AS `extension`,`asterisk`.`queues_config`.`descr` AS `descr`,\'ext-queues\' AS `context`,\'queue\' AS `type` from `asterisk`.`queues_config` union select `asterisk`.`ringgroups`.`grpnum` AS `grpnum`,`asterisk`.`ringgroups`.`description` AS `description`,\'ext-group\' AS `context`,\'ringgroup\' AS `type` from `asterisk`.`ringgroups`
mariadb-version=50568
